Revert "Do not drain on teardown. (#154)"
This reverts commit f189cb4dc04cfa05eae47d0e3502648482d6f593.

diff --git a/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/aws/master_teardown.template b/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/aws/master_teardown.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/aws/master_teardown.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/aws/master_teardown.template
@@ -5,9 +5,14 @@
           ARCH=amd64
           ${FUNCTIONS}
 
+          if ! drain; then
+            echo >&2 "Unable to drain and/or delete on $(hostname)..."
+            exit 68
+          fi
+
           if ! teardown; then
             echo >&2 "Teardown unsuccessful."
-            exit 1
+            exit 69
           fi
 
           echo "Done..."
diff --git a/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/master_teardown.template b/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/master_teardown.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/master_teardown.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/master_teardown.template
@@ -4,6 +4,11 @@
 
           ${FUNCTIONS}
 
+          if ! drain; then
+            echo >&2 "Unable to drain and/or delete on $(hostname)..."
+            exit 1
+          fi
+
           if ! teardown; then
             echo >&2 "Teardown unsuccessful."
             exit 1
