Cleanup yum repo configuration and install createrepo. (#170)

diff --git a/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/common_functions.template b/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/common_functions.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/common_functions.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/common_functions.template
@@ -45,6 +45,9 @@
 
           install_nginx_w_yum()
           {
+            rm -rf /etc/yum.repos.d
+            mkdir -p /etc/yum.repos.d
+
             cat << 'EOF' > /etc/yum.repos.d/centos7.repo
           [epel]
           name=Extra Packages for Enterprise Linux 7 - $basearch
@@ -225,7 +228,7 @@
             setenforce 0
             sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
 
-            toolsImage=$(docker create quay.io/samsung_cnct/cm-vmware-bootstrap:0.1.42)
+            toolsImage=$(docker create quay.io/samsung_cnct/cm-vmware-bootstrap:0.1.42-10)
             echo >&2 "Using boostrap image ${toolsImage}"
 
             if ! docker cp ${toolsImage}:/resources/rpms/ /var/log/rpms;then
@@ -235,6 +238,11 @@
 
             if ! docker cp ${toolsImage}:/resources/yaml/kube-flannel.yml /var/log/kube-flannel.yml;then
               echo >&2 "Unable to copy flannel config from image ${toolsImage}"
+              return 1
+            fi
+
+            if ! yum -y install createrepo ; then
+              echo >&2 "Unable to install createrepo"
               return 1
             fi
 
