Removed ping checks. They are no longer necessary and they may not be reliable in the SDS environment for checking ICMP between subnets.

diff --git a/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/master_bootstrap.template b/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/master_bootstrap.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/master_bootstrap.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/master_bootstrap.template
@@ -42,11 +42,9 @@
           # 10.96.0.11
           export CLUSTER_DNS_SERVER="10.96.0.10"
 
-          if ping -c 1 182.195.81.113; then
-            if ! install_nginx_w_yum; then
-              echo >&2 "Error installing nginx ..."
-              exit 1
-            fi
+          if ! install_nginx_w_yum; then
+            echo >&2 "Error installing nginx ..."
+            exit 1
           fi
 
           if ! install_docker; then
