Separate bootstrap scripts into actual directory repos. Refactor generate script to know how to find templates. Put the original AWS scripts in the centos/aws directories as the SDS scripts and AWS scripts have diverged fairly significantly. (#140)

diff --git a/clusterctl/examples/ssh/bootstrap_scripts/centos/sds/master_bootstrap_7.x.template b/clusterctl/examples/ssh/bootstrap_scripts/centos/sds/master_bootstrap_7.x.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/centos/sds/master_bootstrap_7.x.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/centos/sds/master_bootstrap_7.x.template
@@ -37,13 +37,18 @@
             exit 1
           fi
 
+          # note that this will break if we ever provide a different service_cidr.
+          # also note that the IP address that was being used previously was
+          # 10.96.0.11
           export CLUSTER_DNS_SERVER="10.96.0.10"
 
           cleanup_repos
 
-          if ! install_nginx_w_yum; then
-            echo >&2 "Error installing nginx ..."
-            exit 1
+          if ping -c 1 182.195.81.113; then
+            if ! install_nginx_w_yum; then
+              echo >&2 "Error installing nginx ..."
+              exit 1
+            fi
           fi
 
           if ! install_docker; then
