Removed a few versions from cm template because we ran out of CM space in k8s. Fixed some functions in common_functions. Fixed function name calls where I changed the name of a couple of functions to better names but forgot to fix the callers.

diff --git a/clusterctl/examples/ssh/bootstrap_scripts/common_functions.template b/clusterctl/examples/ssh/bootstrap_scripts/common_functions.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/common_functions.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/common_functions.template
@@ -79,19 +79,24 @@
               return 52
             fi
 
-            newgrp
-            if ! sudo systemctl enable --now docker;then
-              echo >&2 "Unable to 'systemctl enable docker'. Quitting."
-              return 51
-            fi
+            if newgrp; then
+              if ! sudo systemctl enable --now docker;then
+                echo >&2 "Unable to 'systemctl enable docker'. Quitting."
+                return 51
+              fi
 
-            if ! sudo systemctl daemon-reload; then
-              echo >&2 "Unable to reload systemctl daemon."
-              return 51
-            fi
+              if ! sudo systemctl daemon-reload; then
+                echo >&2 "Unable to reload systemctl daemon."
+                return 52
+              fi
 
-            if sudo systemctl restart docker.service; then
-              echo "docker is installed successfully."
+              if sudo systemctl restart docker.service; then
+                echo "docker is installed successfully."
+              fi
+              exit
+            else
+              echo >&2 "Hmm, could not newgrp. Strange. Cannot continue."
+              return 54
             fi
           }
 
