kubeadm reset after 1.10 requires --force for non-interactive remove. Before that, --reset is not a valid argument. Placed an expression in that deals with that.

diff --git a/clusterctl/examples/ssh/bootstrap_scripts/common_functions.template b/clusterctl/examples/ssh/bootstrap_scripts/common_functions.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/common_functions.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/common_functions.template
@@ -441,7 +441,13 @@
 
           teardown()
           {
-            sudo kubeadm reset --force
+            if ! sudo kubeadm reset --force; then
+              echo >&2 "kubeadm version doesn't have 'reset --force' yet probably...trying without."
+              if ! sudo kubeadm reset; then
+                echo >&2 "Hmm, can't kubeadm reset..."
+                return 80
+              fi
+            fi
 
             sudo yum remove -y kubeadm kubectl kubelet kubernetes-cni docker
 
