bug fixes found during testing in AWS. Concerned about the /var/lib/kubelet/config.yaml fix. As I recall, that file gets removed/replaced with k8s > 1.10 so we may have to determine how to set the cgroupfs driver to systemd still.

diff --git a/clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_self-contained_centos_7.template b/clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_self-contained_centos_7.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_self-contained_centos_7.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_self-contained_centos_7.template
@@ -11,9 +11,11 @@
           sudo yum install -y kubeadm-"${KUBELET_VERSION}" --disableexcludes=kubernetes
           sudo yum install -y kubelet-"${KUBELET_VERSION}" --disableexcludes=kubernetes
 
-          if ! sudo sed -r -i 's#cgroupDriver: cgroupfs#cgroupDriver: systemd#' $config; then
-            echo >&2 "Unable to fix kubelet config with proper cgroupfs driver."
-            exit 117
+          if [[ -f /var/lib/kubelet/config.yaml ]]; then
+            if ! sudo sed -r -i 's#cgroupDriver: cgroupfs#cgroupDriver: systemd#' $config; then
+              echo >&2 "Unable to fix kubelet config with proper cgroupfs driver."
+              exit 117
+            fi
           fi
 
           sudo systemctl daemon-reload
diff --git a/clusterctl/examples/ssh/bootstrap_scripts/node_upgrade_self-contained_centos_7.template b/clusterctl/examples/ssh/bootstrap_scripts/node_upgrade_self-contained_centos_7.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/node_upgrade_self-contained_centos_7.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/node_upgrade_self-contained_centos_7.template
@@ -38,9 +38,13 @@
           sudo kubeadm upgrade node config --kubelet-version $(kubelet --version | cut -d ' ' -f 2)
 
           # if this fails, it might be because the upgrade ^^^ failed.
-          if ! sudo sed -r -i 's#cgroupDriver: cgroupfs#cgroupDriver: systemd#' $config; then
-            echo >&2 "Unable to fix kubelet config. The sed command failed."
-            exit 62
+          if [[ -f $config ]]; then
+            if ! sudo sed -r -i 's#cgroupDriver: cgroupfs#cgroupDriver: systemd#' $config; then
+              echo >&2 "Unable to fix kubelet config. The sed command failed."
+              exit 62
+            fi
+          else
+            echo >&2 "WARN: skipping change to $config. It does not exist."
           fi
 
           sudo systemctl daemon-reload
