Notjames cms 391 centos final (#112)
* No longer using air-gapped or aws centos anything; merged everything into current aws work and made everything "centos." Updated upgrade for centos -- will not be using yum; only curl. Updated generate script to handle new file names. Removed SDS_CASE as well.

* Moved yaml templates into their own directory. Last part of file naming change in this commit too.

* latest updates for this fork/branch for collaboration.

* Removed a few versions from cm template because we ran out of CM space in k8s. Fixed some functions in common_functions. Fixed function name calls where I changed the name of a couple of functions to better names but forgot to fix the callers.

* whoops. missed on. Fixed function name in caller on this.

* Upgrade should use yum path. Fixed function call.

* removed superfluous systemctl commands.

* Hmm, exit for newgrp did not behave as expected. Removed.

* minor fixes/updates -- cannot remember what they are now. Committing for Cindy to pull the latest.

* Added --force to kubeadm upgrade apply.

* Found a couple of docker issues. The image we use has Docker-ce 18.03 on it, which was fine for runtime, but does not work for upgrade. Added in docker remove and install with latest centos docker. Other smallish things

* kubeadm reset after 1.10 requires --force for non-interactive remove. Before that, --reset is not a valid argument. Placed an expression in that deals with that.

* Still working through upgrade for master. The guide was mildly helpful. Made relevant changes according to the guide. I have been able to upgrade manually a couple of times while recording the exact steps in the script. However, when I test from the cnotroller, the upgrade fails. I have had similar results using manual testing as well IE try once manually and the tests work, do it again, and they fail yielding different possible reasons in the logs. This commit is iterative.

* upgrade code from Cindy.

* No longer using air-gapped or aws centos anything; merged everything into current aws work and made everything "centos." Updated upgrade for centos -- will not be using yum; only curl. Updated generate script to handle new file names. Removed SDS_CASE as well.

* Moved yaml templates into their own directory. Last part of file naming change in this commit too.

* latest updates for this fork/branch for collaboration.

* Removed a few versions from cm template because we ran out of CM space in k8s. Fixed some functions in common_functions. Fixed function name calls where I changed the name of a couple of functions to better names but forgot to fix the callers.

* whoops. missed on. Fixed function name in caller on this.

* Upgrade should use yum path. Fixed function call.

* removed superfluous systemctl commands.

* Hmm, exit for newgrp did not behave as expected. Removed.

* minor fixes/updates -- cannot remember what they are now. Committing for Cindy to pull the latest.

* Added --force to kubeadm upgrade apply.

* Found a couple of docker issues. The image we use has Docker-ce 18.03 on it, which was fine for runtime, but does not work for upgrade. Added in docker remove and install with latest centos docker. Other smallish things

* kubeadm reset after 1.10 requires --force for non-interactive remove. Before that, --reset is not a valid argument. Placed an expression in that deals with that.

* Still working through upgrade for master. The guide was mildly helpful. Made relevant changes according to the guide. I have been able to upgrade manually a couple of times while recording the exact steps in the script. However, when I test from the cnotroller, the upgrade fails. I have had similar results using manual testing as well IE try once manually and the tests work, do it again, and they fail yielding different possible reasons in the logs. This commit is iterative.

* upgrade code from Cindy.

diff --git a/clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_centos_7.template b/clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_centos_7.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_centos_7.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_centos_7.template
@@ -2,9 +2,11 @@
           set -e
           set -x
           (
-          sudo yum upgrade -y kubectl=${KUBELET_VERSION} --disableexcludes=kubernetes
-          sudo yum upgrade -y kubeadm=${KUBELET_VERSION} --disableexcludes=kubernetes
-          sudo yum upgrade -y kubelet=${KUBELET_VERSION} --disableexcludes=kubernetes
+          ARCH=amd64
+          ${FUNCTIONS}
 
-          sudo systemctl restart kubelet
+          if ! yum_upgrade_master; then
+            echo >&2 "FATAL: upgrade failed. Quitting."
+            exit 117
+          fi
           ) 2>&1 | sudo tee /var/log/upgrade.log
diff --git a/clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_centos_7.template b/clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_centos_7.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_centos_7.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_centos_7.template
@@ -39,12 +39,12 @@
             exit 80
           fi
 
-          if ! install_k8s; then
+          if ! install_k8s_w_yum; then
             echo >&2 "Error installing Kubernetes components..."
             exit 81
           fi
 
-          if ! configure_kubelet; then
+          if ! configure_kubelet_systemd; then
             echo >&2 "Error configuring Kubernetes components..."
             exit 82
           fi
@@ -54,10 +54,10 @@
             exit 83
           fi
 
-          if run_kubeadm_master; then
+          if run_kubeadm_join; then
             echo "Done..."
           else
-            echo >&2 "Error occurred during Kubeadm for master k8s runtime."
+            echo >&2 "Error occurred during Kubeadm join for client node."
             exit 84
           fi
 
