Removal of all functions; everything is inline now.

diff --git a/clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_self-contained_centos_7.template b/clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_self-contained_centos_7.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_self-contained_centos_7.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_self-contained_centos_7.template
@@ -4,30 +4,18 @@
           (
           ARCH=amd64
 
-          fix_kubelet_config()
-          {
-            config="/var/lib/kubelet/config.yaml"
-            sudo sed -r -i 's#cgroupDriver: cgroupfs#cgroupDriver: systemd#' $config
-          }
+          config="/var/lib/kubelet/config.yaml"
 
-          yum_upgrade_master()
-          {
-            # order matters.
-            sudo yum install -y kubectl-"${KUBELET_VERSION}" --disableexcludes=kubernetes
-            sudo yum install -y kubeadm-"${KUBELET_VERSION}" --disableexcludes=kubernetes
-            sudo yum install -y kubelet-"${KUBELET_VERSION}" --disableexcludes=kubernetes
+          # order matters.
+          sudo yum install -y kubectl-"${KUBELET_VERSION}" --disableexcludes=kubernetes
+          sudo yum install -y kubeadm-"${KUBELET_VERSION}" --disableexcludes=kubernetes
+          sudo yum install -y kubelet-"${KUBELET_VERSION}" --disableexcludes=kubernetes
 
-            if ! fix_kubelet_config; then
-              echo >&2 "Unable to fix kubelet config with proper cgroupfs driver."
-              return 1
-            fi
-
-            sudo systemctl daemon-reload
-            sudo systemctl restart kubelet
-          }
-
-          if ! yum_upgrade_master; then
-            echo >&2 "FATAL: upgrade failed. Quitting."
+          if ! sudo sed -r -i 's#cgroupDriver: cgroupfs#cgroupDriver: systemd#' $config; then
+            echo >&2 "Unable to fix kubelet config with proper cgroupfs driver."
             exit 117
           fi
+
+          sudo systemctl daemon-reload
+          sudo systemctl restart kubelet
           ) 2>&1 | sudo tee /var/log/upgrade.log
