No longer using air-gapped or aws centos anything; merged everything into current aws work and made everything "centos." Updated upgrade for centos -- will not be using yum; only curl. Updated generate script to handle new file names. Removed SDS_CASE as well.

diff --git a/clusterctl/examples/ssh/bootstrap_scripts/node_upgrade_centos_7.template b/clusterctl/examples/ssh/bootstrap_scripts/node_upgrade_centos_7.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/node_upgrade_centos_7.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/node_upgrade_centos_7.template
@@ -2,10 +2,13 @@
           set -e
           set -x
           (
-          sudo yum upgrade -y kubectl=${KUBELET_VERSION} --disableexcludes=kubernetes
-          sudo yum upgrade -y kubeadm=${KUBELET_VERSION} --disableexcludes=kubernetes
-          sudo yum upgrade -y kubelet=${KUBELET_VERSION} --disableexcludes=kubernetes
+          ARCH=amd64
+          ${FUNCTIONS}
 
-          sudo kubeadm upgrade node config --kubelet-version $(kubelet --version | cut -d ' ' -f 2)
+          if ! upgrade_node; then
+            echo >&2 "FATAL: upgrade failed. Quitting."
+            exit 80
+          fi
+
           sudo systemctl restart kubelet
           ) 2>&1 | sudo tee /var/log/upgrade.log
