node bootstrap - done

diff --git a/clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_aws_centos_7.template b/clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_aws_centos_7.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_aws_centos_7.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_aws_centos_7.template
@@ -34,25 +34,30 @@
           CLUSTER_DNS_SERVER="$(prips "${SERVICE_CIDR}")"
           export CLUSTER_DNS_SERVER
 
-          if install_docker; then
-            if install_k8s; then
-              if configure_kubelet; then
-                if configure_kubeadm; then
-                  if run_kubeadm; then
-                    echo "Done..."
-                  else
-                    exit 80
-                  fi
-                else
-                  exit 81
-                fi
-              else
-                exit 82
-              fi
-            else
-              exit 83
-            fi
+          if ! install_docker; then
+            echo >&2 "Error installing docker components..."
+            exit 80
+          fi
+
+          if ! install_k8s; then
+            echo >&2 "Error installing Kubernetes components..."
+            exit 81
+          fi
+
+          if ! configure_kubelet; then
+            echo >&2 "Error configuring Kubernetes components..."
+            exit 82
+          fi
+
+          if ! configure_kubeadm; then
+            echo >&2 "Error configuring kubeadm componenets..."
+            exit 83
+          fi
+
+          if run_kubeadm_join; then
+            echo "Done..."
           else
+            echo >&2 "Error occurred during Kubeadm for master k8s runtime."
             exit 84
           fi
 
