add centos yum repo and nginx installation

diff --git a/clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_centos_7.template b/clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_centos_7.template
--- a/clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_centos_7.template
+++ b/clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_centos_7.template
@@ -39,6 +39,11 @@
             exit 80
           fi
 
+          if ! install_nginx_w_yum; then
+            echo >&2 "Error installing nginx ..."
+            exit 1
+          fi
+
           if ! install_k8s_w_yum; then
             echo >&2 "Error installing Kubernetes components..."
             exit 81
